interface Photo {
  id: string;
  name: string;
  sku: string;
  description: string;
  price: number;
  weight: number;
  weightUnit: string;
  length: number;
  width: number;
  height: number;
  customizable: boolean;
  freeShipping: boolean;
  qtyInStock: number;
  productId: number;
  categoryId: string;
  imageUrl: string;
}
export const allPhotos: Photo[] = [
    {
      id: "1",
      name: "Majestic Lion",
      sku: "WL-001",
      description: "A powerful lion roaring in the savanna.",
      price: 49.99,
      weight: 0.5,
      weightUnit: "kg",
      length: 30,
      width: 20,
      height: 1,
      customizable: true,
      freeShipping: false,
      qtyInStock: 10,
      productId: 101,
      categoryId: "mammals",
      imageUrl: "https://res.cloudinary.com/dadtqnsr4/image/upload/v1760732346/DSC02494_vzzs7l.jpg",
    },
    {
      id: "2",
      name: "Eagle in Flight",
      sku: "WL-002",
      description: "Bald eagle soaring over mountains.",
      price: 59.99,
      weight: 0.6,
      weightUnit: "kg",
      length: 40,
      width: 30,
      height: 1,
      customizable: false,
      freeShipping: true,
      qtyInStock: 5,
      productId: 102,
      categoryId: "birds",
      imageUrl: "https://res.cloudinary.com/dadtqnsr4/image/upload/v1760732344/DSC02477_atf5ui.jpg",
    },
    {
      id: "3",
      name: "Coral Reef Fish",
      sku: "WL-003",
      description: "Vibrant tropical fish in a coral reef.",
      price: 39.99,
      weight: 0.4,
      weightUnit: "kg",
      length: 25,
      width: 25,
      height: 1,
      customizable: true,
      freeShipping: false,
      qtyInStock: 15,
      productId: 103,
      categoryId: "marine",
      imageUrl: "https://res.cloudinary.com/dadtqnsr4/image/upload/v1760732343/DSC02476_i23gom.jpg",
    },
    {
      id: "4",
      name: "Butterfly Macro",
      sku: "WL-004",
      description: "Close-up of a colorful butterfly on a flower.",
      price: 29.99,
      weight: 0.3,
      weightUnit: "kg",
      length: 20,
      width: 20,
      height: 1,
      customizable: false,
      freeShipping: true,
      qtyInStock: 20,
      productId: 104,
      categoryId: "insects",
      imageUrl: "https://res.cloudinary.com/dadtqnsr4/image/upload/v1760732342/DSC02429_klnvfs.jpg",
    },
    {
      id: "5",
      name: "Elephant Herd",
      sku: "WL-005",
      description: "Family of elephants at a waterhole.",
      price: 69.99,
      weight: 0.7,
      weightUnit: "kg",
      length: 50,
      width: 30,
      height: 1,
      customizable: true,
      freeShipping: false,
      qtyInStock: 8,
      productId: 105,
      categoryId: "mammals",
      imageUrl: "https://res.cloudinary.com/dadtqnsr4/image/upload/v1760732339/DSC02376_1_rapvpr.jpg",
    },
    {
      id: "6",
      name: "Owl at Night",
      sku: "WL-006",
      description: "Nocturnal owl perched on a branch.",
      price: 44.99,
      weight: 0.5,
      weightUnit: "kg",
      length: 30,
      width: 20,
      height: 1,
      customizable: false,
      freeShipping: false,
      qtyInStock: 12,
      productId: 106,
      categoryId: "birds",
      imageUrl: "https://res.cloudinary.com/dadtqnsr4/image/upload/v1760732337/DSC02274_hvc9my.jpg",
    },
    {
      id: "7",
      name: "Shark Underwater",
      sku: "WL-007",
      description: "Great white shark gliding through the ocean.",
      price: 79.99,
      weight: 0.8,
      weightUnit: "kg",
      length: 40,
      width: 40,
      height: 1,
      customizable: true,
      freeShipping: true,
      qtyInStock: 3,
      productId: 107,
      categoryId: "marine",
      imageUrl: "https://res.cloudinary.com/dadtqnsr4/image/upload/v1760732329/DSC02135_usm4yu.jpg",
    },
    {
      id: "8",
      name: "Komodo Dragon",
      sku: "WL-008",
      description: "Fierce Komodo dragon on rocky terrain.",
      price: 54.99,
      weight: 0.6,
      weightUnit: "kg",
      length: 35,
      width: 25,
      height: 1,
      customizable: false,
      freeShipping: false,
      qtyInStock: 7,
      productId: 108,
      categoryId: "reptiles",
      imageUrl: "https://res.cloudinary.com/dadtqnsr4/image/upload/v1760732328/DSC02124_pbls0q.jpg",
    },
    // Add more static photos as needed for variety
  ];